export function getPanelScript(): string {
  const lines = [
    '    const vscode = acquireVsCodeApi();',
    '    const messagesEl = document.getElementById(\'messages\');',
    '    const inputEl = document.getElementById(\'input\');',
    '    const sendBtn = document.getElementById(\'sendBtn\');',
    '    const tabsEl = document.getElementById(\'chatTabs\');',
    '',
    '    const LLM_ONLY_CHAT_ID = \'llm-only\';',
    '    let chats = [{ id: LLM_ONLY_CHAT_ID, name: \'Чат с LLM\', messages: [] }];',
    '    let openIds = [LLM_ONLY_CHAT_ID];',
    '    let activeId = LLM_ONLY_CHAT_ID;',
    '    const historyBtn = document.getElementById(\'historyBtn\');',
    '    const historyDropdown = document.getElementById(\'historyDropdown\');',
    '    const clearChatBtn = document.getElementById(\'clearChatBtn\');',
    '    const contextFooter = document.getElementById(\'contextFooter\');',
    '    const diffView = document.getElementById(\'diffView\');',
    '    const diffViewFiles = document.getElementById(\'diffViewFiles\');',
    '    const diffApplyBtn = document.getElementById(\'diffApplyBtn\');',
    '    const diffRejectBtn = document.getElementById(\'diffRejectBtn\');',
    '    let contextLimit = 128000;',
    '    var contextByChat = {};',
    '    var lastProjectContextChars = 0;',
    '    var pendingDiffByChat = {};',
    '    var disableApply = false;',
    '    var attachedFiles = []; // { path, fromLine, toLine }',
    '',
    '    function renderAttachedFiles() {',
    '      var el = document.getElementById(\'attachedFiles\');',
    '      if (!el) return;',
    '      el.innerHTML = \'\';',
    '      if (!attachedFiles.length) { el.style.display = \'none\'; return; }',
    '      el.style.display = \'flex\';',
    '      attachedFiles.forEach(function (f, idx) {',
    '        var tag = document.createElement(\'div\');',
    '        tag.className = \'attached-file-tag\';',
    '        var name = document.createElement(\'span\');',
    '        name.className = \'af-name\';',
    '        name.textContent = f.path.split(/[\\/\\\\]/).pop();',
    '        name.title = f.path;',
    '        tag.appendChild(name);',
    '        if (typeof f.fromLine === \'number\') {',
    '          var range = document.createElement(\'span\');',
    '          range.className = \'af-range\';',
    '          range.textContent = typeof f.toLine === \'number\' && f.toLine !== f.fromLine',
    '            ? \' :\' + f.fromLine + \'–\' + f.toLine',
    '            : \' :\' + f.fromLine;',
    '          tag.appendChild(range);',
    '        }',
    '        var rm = document.createElement(\'button\');',
    '        rm.className = \'af-remove\';',
    '        rm.title = \'Открепить файл\';',
    '        rm.innerHTML = \'&times;\';',
    '        (function (i) { rm.onclick = function () { attachedFiles.splice(i, 1); renderAttachedFiles(); }; })(idx);',
    '        tag.appendChild(rm);',
    '        el.appendChild(tag);',
    '      });',
    '    }',
    '',
    '    function attachFile(path, fromLine, toLine) {',
    '      var exists = attachedFiles.findIndex(function (f) { return f.path === path; });',
    '      if (exists >= 0) { attachedFiles[exists].fromLine = fromLine; attachedFiles[exists].toLine = toLine; }',
    '      else attachedFiles.push({ path: path, fromLine: fromLine, toLine: toLine });',
    '      renderAttachedFiles();',
    '    }',
    '    var loaderMinElapsed = false;',
    '    var indexBuildInProgress = false;',
    '    var loaderClosed = false;',
    '',
    '    function closeStarfieldOverlay() {',
    '      if (loaderClosed) return;',
    '      var overlay = document.getElementById(\'starfield-overlay\');',
    '      if (!overlay) { loaderClosed = true; return; }',
    '      loaderClosed = true;',
    '      overlay.classList.add(\'starfield-out\');',
    '      setTimeout(function () { if (overlay && overlay.parentNode) overlay.parentNode.removeChild(overlay); }, 950);',
    '    }',
    '    function syncStarfieldOverlay() {',
    '      if (loaderClosed) return;',
    '      if (!loaderMinElapsed) return;',
    '      if (indexBuildInProgress) return;',
    '      closeStarfieldOverlay();',
    '    }',
    '',
    '    function diffLines(orig, prop) {',
    '      var a = (orig || \'\').split(\'\\n\');',
    '      var b = (prop || \'\').split(\'\\n\');',
    '      var n = a.length, m = b.length;',
    '      var dp = []; for (var i = 0; i <= n; i++) { dp[i] = []; for (var j = 0; j <= m; j++) dp[i][j] = 0; }',
    '      for (var i = 1; i <= n; i++) for (var j = 1; j <= m; j++) dp[i][j] = a[i-1] === b[j-1] ? dp[i-1][j-1] + 1 : Math.max(dp[i-1][j], dp[i][j-1]);',
    '      var out = []; var i = n, j = m;',
    '      while (i > 0 || j > 0) {',
    '        if (i > 0 && j > 0 && a[i-1] === b[j-1]) { out.unshift({ type: \'same\', line: a[i-1] }); i--; j--; }',
    '        else if (j > 0 && (i === 0 || dp[i][j-1] >= dp[i-1][j])) { out.unshift({ type: \'add\', line: b[j-1] }); j--; }',
    '        else { out.unshift({ type: \'remove\', line: a[i-1] }); i--; }',
    '      }',
    '      return out;',
    '    }',
    '    function renderDiffView(files) {',
    '      if (!diffViewFiles) return;',
    '      diffViewFiles.innerHTML = \'\';',
    '      var created = [];',
    '      var modified = [];',
    '      files.forEach(function (f) {',
    '        var isNew = !(f.originalContent && f.originalContent.trim().length > 0);',
    '        if (isNew) created.push(f.path); else modified.push(f.path);',
    '      });',
    '      var summaryEl = document.getElementById(\'diffViewSummary\');',
    '      if (summaryEl) {',
    '        var parts = [];',
    '        if (created.length) parts.push(\'Созданы: \' + created.join(\', \'));',
    '        if (modified.length) parts.push(\'Изменены: \' + modified.join(\', \'));',
    '        summaryEl.textContent = parts.join(\'. \') || \'\';',
    '      }',
    '      files.forEach(function (f) {',
    '        var block = document.createElement(\'div\');',
    '        block.className = \'diff-file-block\';',
    '        var title = document.createElement(\'div\');',
    '        title.className = \'diff-file-title\';',
    '        var isNew = !(f.originalContent && f.originalContent.trim().length > 0);',
    '        var badge = document.createElement(\'span\');',
    '        badge.className = \'diff-badge \' + (isNew ? \'diff-badge-new\' : \'diff-badge-modified\');',
    '        badge.textContent = isNew ? \'Новый файл\' : \'Изменён\';',
    '        var pathSpan = document.createElement(\'span\');',
    '        pathSpan.className = \'diff-file-path\';',
    '        pathSpan.textContent = f.path;',
    '        var openBtn = document.createElement(\'button\');',
    '        openBtn.className = \'diff-open-file-btn\';',
    '        openBtn.textContent = \'Открыть\';',
    '        openBtn.title = \'Открыть файл в редакторе\';',
    '        openBtn.onclick = function () { vscode.postMessage({ type: \'openFile\', path: f.path }); };',
    '        title.appendChild(badge);',
    '        title.appendChild(pathSpan);',
    '        title.appendChild(openBtn);',
    '        block.appendChild(title);',
    '        var pre = document.createElement(\'pre\');',
    '        pre.className = \'diff-file-content\';',
    '        var chunks = diffLines(f.originalContent, f.proposedContent);',
    '        chunks.forEach(function (c) {',
    '          var span = document.createElement(\'span\');',
    '          span.className = \'diff-line diff-\' + c.type;',
    '          span.textContent = (c.line || \'\') + \'\\n\';',
    '          pre.appendChild(span);',
    '        });',
    '        block.appendChild(pre);',
    '        diffViewFiles.appendChild(block);',
    '      });',
    '      if (diffView) diffView.style.display = \'block\';',
    '      if (diffApplyBtn) diffApplyBtn.style.display = disableApply ? \'none\' : \'\';',
    '    }',
    '    function hideDiffView(clearStorage) {',
    '      if (diffView) diffView.style.display = \'none\';',
    '      if (diffViewFiles) diffViewFiles.innerHTML = \'\';',
    '      var summaryEl = document.getElementById(\'diffViewSummary\');',
    '      if (summaryEl) summaryEl.textContent = \'\';',
    '      if (clearStorage !== false && activeId) delete pendingDiffByChat[activeId];',
    '    }',
    '',
    '    function renderTabs() {',
    '      tabsEl.innerHTML = \'\';',
    '      openIds.forEach(function (id) {',
    '        const c = chats.find(function (ch) { return ch.id === id; });',
    '        if (!c) return;',
    '        const wrap = document.createElement(\'div\');',
    '        wrap.className = \'tab-wrap\' + (c.id === activeId ? \' active\' : \'\') + (c.id === LLM_ONLY_CHAT_ID ? \' tab-llm-only\' : \'\');',
    '        const btn = document.createElement(\'button\');',
    '        btn.className = \'tab\';',
    '        btn.textContent = c.name;',
    '        btn.addEventListener(\'click\', function () { switchChat(c.id); });',
    '        wrap.appendChild(btn);',
    '        if (openIds.length > 1 && c.id !== LLM_ONLY_CHAT_ID) {',
    '          const closeBtn = document.createElement(\'button\');',
    '          closeBtn.className = \'tab-close\';',
    '          closeBtn.innerHTML = \'&times;\';',
    '          closeBtn.title = \'Закрыть вкладку\';',
    '          closeBtn.addEventListener(\'click\', function (e) { closeTab(c.id, e); });',
    '          wrap.appendChild(closeBtn);',
    '        }',
    '        tabsEl.appendChild(wrap);',
    '      });',
    '      const newBtn = document.createElement(\'button\');',
    '      newBtn.className = \'tab tab-new\';',
    '      newBtn.textContent = \'+ Новый чат\';',
    '      newBtn.addEventListener(\'click\', addChat);',
    '      tabsEl.appendChild(newBtn);',
    '      if (clearChatBtn) clearChatBtn.style.display = activeId === LLM_ONLY_CHAT_ID ? \'block\' : \'none\';',
    '    }',
    '',
    '    function clearLlmChat() {',
    '      const chat = chats.find(function (c) { return c.id === LLM_ONLY_CHAT_ID; });',
    '      if (!chat) return;',
    '      chat.messages = [];',
    '      vscode.postMessage({ type: \'persistChat\', chatId: chat.id, name: chat.name, messages: [] });',
    '      renderMessages();',
    '    }',
    '',
    '    function escapeHtml(s) {',
    '      var d = document.createElement(\'div\');',
    '      d.textContent = s;',
    '      return d.innerHTML;',
    '    }',
    '    function formatTextOnly(text) {',
    '      if (!text) return \'\';',
    '      var t = escapeHtml(text);',
    '      var backtick = String.fromCharCode(96);',
    '      t = t.replace(/^### (.+)$/gm, \'<h3 class="msg-h3">$1</h3>\');',
    '      t = t.replace(/^## (.+)$/gm, \'<h2 class="msg-h2">$1</h2>\');',
    '      t = t.replace(/^# (.+)$/gm, \'<h1 class="msg-h1">$1</h1>\');',
    '      t = t.replace(/^&gt; ?(.+)$/gm, \'<blockquote class="msg-blockquote">$1</blockquote>\');',
    '      t = t.replace(/\\*\\*(.*?)\\*\\*/g, \'<strong>$1</strong>\');',
    '      t = t.replace(/\\*(.*?)\\*/g, \'<em>$1</em>\');',
    '      t = t.replace(new RegExp(backtick + \'([^\' + backtick + \']+)\' + backtick, \'g\'), \'<code class="msg-inline-code">$1</code>\');',
    '      t = t.replace(/^(\\d+)\\.\\s+/gm, \'<span class="msg-num">$1.</span> \');',
    '      t = t.replace(/^[-*]\\s+/gm, \'<span class="msg-bullet">•</span> \');',
    '      t = t.replace(/\\n/g, \'<br>\');',
    '      return t;',
    '    }',
    '    function parseMessageToParts(text) {',
    '      var parts = [];',
    '      var backtick = String.fromCharCode(96);',
    '      var codeRe = new RegExp(backtick + backtick + backtick + \'(\\\\w*)\\\\s*\\\\n([\\\\s\\\\S]*?)\' + backtick + backtick + backtick, \'g\');',
    '      var lastIndex = 0;',
    '      var match;',
    '      while ((match = codeRe.exec(text)) !== null) {',
    '        if (match.index > lastIndex) parts.push({ type: \'text\', value: text.slice(lastIndex, match.index) });',
    '        parts.push({ type: \'code\', lang: (match[1] || \'\').trim(), code: (match[2] || \'\').trim() });',
    '        lastIndex = match.index + match[0].length;',
    '      }',
    '      parts.push({ type: \'text\', value: text.slice(lastIndex) });',
    '      return parts;',
    '    }',
    '    function createCodeBlock(lang, code) {',
    '      var wrap = document.createElement(\'div\');',
    '      wrap.className = \'code-preview-block\';',
    '      var codeHeader = document.createElement(\'div\');',
    '      codeHeader.className = \'code-block-header\';',
    '      codeHeader.textContent = lang || \'Код\';',
    '      wrap.appendChild(codeHeader);',
    '      var codeScroll = document.createElement(\'div\');',
    '      codeScroll.className = \'code-block-scroll\';',
    '      var codePre = document.createElement(\'pre\');',
    '      codePre.textContent = code;',
    '      codeScroll.appendChild(codePre);',
    '      wrap.appendChild(codeScroll);',
    '      var codeActions = document.createElement(\'div\');',
    '      codeActions.className = \'code-preview-actions\';',
    '      var copyBtn = document.createElement(\'button\');',
    '      copyBtn.className = \'code-copy-btn\';',
    '      copyBtn.textContent = \'Копировать\';',
    '      copyBtn.onclick = function () {',
    '        navigator.clipboard.writeText(code).then(function () { copyBtn.textContent = \'Скопировано!\'; setTimeout(function () { copyBtn.textContent = \'Копировать\'; }, 2000); }).catch(function () { copyBtn.textContent = \'Ошибка\'; setTimeout(function () { copyBtn.textContent = \'Копировать\'; }, 2000); });',
    '      };',
    '      codeActions.appendChild(copyBtn);',
    '      wrap.appendChild(codeActions);',
    '      return wrap;',
    '    }',
    '    function buildAssistantContent(text) {',
    '      var container = document.createElement(\'div\');',
    '      container.className = \'message-content\';',
    '      var parts = parseMessageToParts(text);',
    '      for (var i = 0; i < parts.length; i++) {',
    '        if (parts[i].type === \'text\' && parts[i].value.trim()) {',
    '          var textEl = document.createElement(\'div\');',
    '          textEl.className = \'message-text\';',
    '          textEl.innerHTML = formatTextOnly(parts[i].value);',
    '          container.appendChild(textEl);',
    '        } else if (parts[i].type === \'code\' && parts[i].code) {',
    '          container.appendChild(createCodeBlock(parts[i].lang, parts[i].code));',
    '        }',
    '      }',
    '      return container;',
    '    }',
    '    function renderMessages() {',
    '      const chat = chats.find(function (c) { return c.id === activeId; });',
    '      messagesEl.innerHTML = \'\';',
    '      if (chat) {',
    '        chat.messages.forEach(function (m) {',
    '          const div = document.createElement(\'div\');',
    '          div.className = \'message \' + m.role + (m.error ? \' message-error\' : \'\');',
    '          if (m.role === \'assistant\') {',
    '            if (m.typing) {',
    '              const content = document.createElement(\'div\');',
    '              content.className = \'message-content typing-indicator\';',
    '              content.textContent = m.text || \'...\';',
    '              div.appendChild(content);',
    '            } else {',
    '              if (m.thinkReasoning) {',
    '                var thinkEl = document.createElement(\'details\');',
    '                thinkEl.className = \'think-block\';',
    '                var thinkSum = document.createElement(\'summary\');',
    '                thinkSum.className = \'think-summary\';',
    '                thinkSum.textContent = \'Рассуждение\';',
    '                var thinkBody = document.createElement(\'div\');',
    '                thinkBody.className = \'think-body\';',
    '                thinkBody.textContent = m.thinkReasoning;',
    '                thinkEl.appendChild(thinkSum);',
    '                thinkEl.appendChild(thinkBody);',
    '                div.appendChild(thinkEl);',
    '              }',
    '              div.appendChild(buildAssistantContent(m.text));',
    '              if (m.error) {',
    '                const retryBtn = document.createElement(\'button\');',
    '                retryBtn.className = \'message-retry-btn\';',
    '                retryBtn.textContent = \'Повторить\';',
    '                retryBtn.onclick = function () { retryLast(chat.id); };',
    '                div.appendChild(retryBtn);',
    '              }',
    '            }',
    '          } else {',
    '            const content = document.createElement(\'div\');',
    '            content.className = \'message-content\';',
    '            content.textContent = m.text;',
    '            div.appendChild(content);',
    '          }',
    '          messagesEl.appendChild(div);',
    '        });',
    '        messagesEl.scrollTop = messagesEl.scrollHeight;',
    '      }',
    '    }',
    '',
    '    function saveState() {',
    '      vscode.postMessage({ type: \'savePanelState\', openIds: openIds, activeId: activeId });',
    '    }',
    '',
    '    function renderContextFooter() {',
    '      if (!contextFooter) return;',
    '      var data = contextByChat[activeId];',
    '      var base = \'\';',
    '      if (data && typeof data.used === \'number\') {',
    '        var left = Math.max(0, (data.limit || contextLimit) - data.used);',
    '        base = \'Контекст: \' + data.used.toLocaleString() + \' / \' + (data.limit || contextLimit).toLocaleString() + \' (осталось \' + left.toLocaleString() + \')\';',
    '      } else {',
    '        base = \'Контекст: — / \' + contextLimit.toLocaleString();',
    '      }',
    '      if (lastProjectContextChars > 0) base += \' | Контекст проекта (в промпт): \' + lastProjectContextChars.toLocaleString() + \' симв.\';',
    '      if (data && Array.isArray(data.tools) && data.tools.length > 0) {',
    '        var unique = data.tools.filter(function (v, i, a) { return a.indexOf(v) === i; });',
    '        base += \' | Tools: \' + unique.join(\', \');',
    '      }',
    '      contextFooter.textContent = base;',
    '    }',
    '',
    '    function switchChat(id) {',
    '      activeId = id;',
    '      renderTabs();',
    '      renderMessages();',
    '      renderContextFooter();',
    '      saveState();',
    '      if (clearChatBtn) clearChatBtn.style.display = activeId === LLM_ONLY_CHAT_ID ? \'block\' : \'none\';',
    '      if (pendingDiffByChat[activeId]) renderDiffView(pendingDiffByChat[activeId].files); else hideDiffView(false);',
    '    }',
    '',
    '    function addChat() {',
    '      const id = String(Date.now());',
    '      const projectCount = chats.filter(function (c) { return c.id !== LLM_ONLY_CHAT_ID; }).length;',
    '      const name = \'Чат \' + (projectCount + 1);',
    '      chats.push({ id: id, name: name, messages: [] });',
    '      openIds.push(id);',
    '      switchChat(id);',
    '      saveState();',
    '      vscode.postMessage({ type: \'persistChat\', chatId: id, name: name, messages: [] });',
    '    }',
    '',
    '    function closeTab(chatId, e) {',
    '      e.stopPropagation();',
    '      if (chatId === LLM_ONLY_CHAT_ID || openIds.length <= 1) return;',
    '      const idx = openIds.indexOf(chatId);',
    '      if (idx < 0) return;',
    '      openIds.splice(idx, 1);',
    '      if (activeId === chatId) {',
    '        activeId = openIds[0];',
    '        renderTabs();',
    '        renderMessages();',
    '      } else {',
    '        renderTabs();',
    '      }',
    '      saveState();',
    '    }',
    '',
    '    function openChatFromHistory(id) {',
    '      if (openIds.indexOf(id) < 0) openIds.push(id);',
    '      switchChat(id);',
    '      historyDropdown.classList.remove(\'visible\');',
    '      renderTabs();',
    '      renderMessages();',
    '      saveState();',
    '    }',
    '',
    '    function deleteChat(chatId) {',
    '      if (chatId === LLM_ONLY_CHAT_ID) return;',
    '      const chatIdx = chats.findIndex(function (c) { return c.id === chatId; });',
    '      if (chatIdx < 0) return;',
    '      chats.splice(chatIdx, 1);',
    '      const openIdx = openIds.indexOf(chatId);',
    '      if (openIdx >= 0) openIds.splice(openIdx, 1);',
    '      vscode.postMessage({ type: \'removeChat\', chatId: chatId });',
    '      if (activeId === chatId) {',
    '        activeId = openIds.length > 0 ? openIds[0] : LLM_ONLY_CHAT_ID;',
    '        renderTabs();',
    '        renderMessages();',
    '      } else { renderTabs(); }',
    '      saveState();',
    '      renderHistoryDropdown();',
    '    }',
    '',
    '    function renderHistoryDropdown() {',
    '      historyDropdown.innerHTML = \'\';',
    '      chats.forEach(function (c) {',
    '        const row = document.createElement(\'div\');',
    '        row.className = \'history-item\';',
    '        const nameEl = document.createElement(\'span\');',
    '        nameEl.className = \'history-item-name\';',
    '        nameEl.textContent = c.name;',
    '        nameEl.title = c.name;',
    '        row.appendChild(nameEl);',
    '        const actions = document.createElement(\'div\');',
    '        actions.className = \'history-item-actions\';',
    '        const openBtn = document.createElement(\'button\');',
    '        openBtn.className = \'history-item-btn\';',
    '        openBtn.textContent = openIds.indexOf(c.id) >= 0 ? \'Открыт\' : \'Открыть\';',
    '        openBtn.disabled = openIds.indexOf(c.id) >= 0;',
    '        openBtn.onclick = function () { openChatFromHistory(c.id); };',
    '        const renameBtn = document.createElement(\'button\');',
    '        renameBtn.className = \'history-item-btn\';',
    '        renameBtn.textContent = \'Переименовать\';',
    '        renameBtn.onclick = function () {',
    '          var newName = window.prompt(\'Название чата\', c.name);',
    '          if (newName != null && (newName = newName.trim())) { c.name = newName; vscode.postMessage({ type: \'persistChat\', chatId: c.id, name: c.name, messages: c.messages }); renderTabs(); renderHistoryDropdown(); }',
    '        };',
    '        const delBtn = document.createElement(\'button\');',
    '        delBtn.className = \'history-item-btn delete\';',
    '        delBtn.textContent = \'Удалить\';',
    '        delBtn.onclick = function () { deleteChat(c.id); };',
    '        if (c.id === LLM_ONLY_CHAT_ID) delBtn.style.display = \'none\';',
    '        actions.appendChild(openBtn);',
    '        actions.appendChild(renameBtn);',
    '        actions.appendChild(delBtn);',
    '        row.appendChild(actions);',
    '        historyDropdown.appendChild(row);',
    '      });',
    '    }',
    '',
    '    function send() {',
    '      const text = inputEl.value.trim();',
    '      if (!text) return;',
    '      const chat = chats.find(function (c) { return c.id === activeId; });',
    '      const messages = chat ? chat.messages : [];',
    '      var files = attachedFiles.slice();',
    '      vscode.postMessage({ type: \'send\', text: text, chatId: activeId, messages: messages, noProjectContext: activeId === LLM_ONLY_CHAT_ID, attachedFiles: files });',
    '      inputEl.value = \'\';',
    '      attachedFiles = [];',
    '      renderAttachedFiles();',
    '    }',
    '',
    '    function addMessageToChat(chatId, text, role, isError) {',
    '      const chat = chats.find(function (c) { return c.id === chatId; });',
    '      if (!chat) return;',
    '      if (role === \'assistant\') {',
    '        var last = chat.messages[chat.messages.length - 1];',
    '        if (last && last.typing) {',
    '          last.role = \'assistant\';',
    '          last.text = text;',
    '          last.typing = undefined;',
    '          if (isError) last.error = true;',
    '        } else {',
    '          var msg = { role: \'assistant\', text: text };',
    '          if (isError) msg.error = true;',
    '          chat.messages.push(msg);',
    '        }',
    '      } else {',
    '        chat.messages.push({ role: role, text: text });',
    '      }',
    '      if (chatId === activeId) renderMessages();',
    '      vscode.postMessage({ type: \'persistChat\', chatId: chat.id, name: chat.name, messages: chat.messages.map(function (m) { return { role: m.role, text: m.text }; }) });',
    '    }',
    '',
    '    function addTypingPlaceholder(chatId) {',
    '      const chat = chats.find(function (c) { return c.id === chatId; });',
    '      if (chat) { chat.messages.push({ role: \'assistant\', text: \'\', typing: true }); if (chatId === activeId) renderMessages(); }',
    '    }',
    '',
    '    function retryLast(chatId) {',
    '      const chat = chats.find(function (c) { return c.id === chatId; });',
    '      if (!chat || chat.messages.length === 0) return;',
    '      var last = chat.messages[chat.messages.length - 1];',
    '      if (last.role !== \'assistant\' || !last.error) return;',
    '      chat.messages.pop();',
    '      chat.messages.push({ role: \'assistant\', text: \'\', typing: true });',
    '      renderMessages();',
    '      var history = chat.messages.slice(0, -1).map(function (m) { return { role: m.role, text: m.text }; });',
    '      vscode.postMessage({ type: \'retry\', chatId: chatId, messages: history, noProjectContext: chatId === LLM_ONLY_CHAT_ID });',
    '    }',
    '',
    '    if (clearChatBtn) clearChatBtn.addEventListener(\'click\', function () { clearLlmChat(); });',
    '    historyBtn.addEventListener(\'click\', function (e) {',
    '      e.stopPropagation();',
    '      historyDropdown.classList.toggle(\'visible\');',
    '      if (historyDropdown.classList.contains(\'visible\')) renderHistoryDropdown();',
    '    });',
    '    document.addEventListener(\'click\', function () { historyDropdown.classList.remove(\'visible\'); });',
    '    historyDropdown.addEventListener(\'click\', function (e) { e.stopPropagation(); });',
    '',
    '    inputEl.addEventListener(\'keydown\', function (e) {',
    '      if (e.key === \'Enter\' && e.ctrlKey) { e.preventDefault(); send(); }',
    '    });',
    '    sendBtn.addEventListener(\'click\', send);',
    '    if (diffApplyBtn) diffApplyBtn.addEventListener(\'click\', function () { vscode.postMessage({ type: \'applyEdits\', chatId: activeId }); });',
    '    if (diffRejectBtn) diffRejectBtn.addEventListener(\'click\', hideDiffView);',
    '',
    '    window.addEventListener(\'message\', function (event) {',
    '      const msg = event.data;',
    '      if (msg.type === \'history\' && Array.isArray(msg.chats)) {',
    '        if (msg.chats.length > 0) {',
    '          chats = msg.chats;',
    '          if (!chats.some(function (c) { return c.id === LLM_ONLY_CHAT_ID; })) chats.unshift({ id: LLM_ONLY_CHAT_ID, name: \'Чат с LLM\', messages: [] });',
    '          var projectChats = chats.filter(function (c) { return c.id !== LLM_ONLY_CHAT_ID; });',
    '          for (var i = 0; i < projectChats.length; i++) projectChats[i].name = \'Чат \' + (i + 1);',
    '          var savedOpenIds = Array.isArray(msg.openIds) ? msg.openIds : null;',
    '          var savedActiveId = typeof msg.activeId === \'string\' ? msg.activeId : null;',
    '          if (savedOpenIds && savedOpenIds.length > 0) {',
    '            openIds = savedOpenIds.filter(function (id) { return chats.some(function (c) { return c.id === id; }); });',
    '            if (openIds.length === 0) openIds = [LLM_ONLY_CHAT_ID];',
    '          } else { openIds = chats.map(function (c) { return c.id; }); }',
    '          if (savedActiveId && chats.some(function (c) { return c.id === savedActiveId; })) activeId = savedActiveId;',
    '          else activeId = openIds[0];',
    '          chats.forEach(function (c) {',
    '            vscode.postMessage({ type: \'persistChat\', chatId: c.id, name: c.name, messages: c.messages });',
    '          });',
    '        }',
    '        if (typeof msg.contextLimit === \'number\') { contextLimit = msg.contextLimit; }',
    '        if (typeof msg.disableApply === \'boolean\') { disableApply = msg.disableApply; if (diffApplyBtn) diffApplyBtn.style.display = disableApply ? \'none\' : \'\'; }',
    '        renderTabs();',
    '        renderMessages();',
    '        renderContextFooter();',
    '        return;',
    '      }',
    '      if (msg.type === \'replaceHistory\' && msg.chatId && Array.isArray(msg.messages)) {',
    '        var ch = chats.find(function (c) { return c.id === msg.chatId; });',
    '        if (ch) { ch.messages = msg.messages.map(function (m) { return { role: m.role, text: m.text }; }); if (msg.chatId === activeId) renderMessages(); vscode.postMessage({ type: \'persistChat\', chatId: ch.id, name: ch.name, messages: ch.messages.map(function (m) { return { role: m.role, text: m.text }; }) }); }',
    '        return;',
    '      }',
    '      if (msg.type === \'userMessage\' && msg.text && msg.chatId) {',
    '        addMessageToChat(msg.chatId, msg.text, \'user\');',
    '        addTypingPlaceholder(msg.chatId);',
    '      }',
    '      if (msg.type === \'assistantMessage\' && msg.chatId) {',
    '        addMessageToChat(msg.chatId, msg.text || \'\', \'assistant\', msg.isError);',
    '        if (typeof msg.contextUsed === \'number\' || typeof msg.contextLimit === \'number\') {',
    '          if (!contextByChat[msg.chatId]) contextByChat[msg.chatId] = {};',
    '          if (typeof msg.contextUsed === \'number\') contextByChat[msg.chatId].used = msg.contextUsed;',
    '          if (typeof msg.contextLimit === \'number\') { contextLimit = msg.contextLimit; contextByChat[msg.chatId].limit = msg.contextLimit; }',
    '          if (Array.isArray(msg.toolsUsed) && msg.toolsUsed.length > 0) contextByChat[msg.chatId].tools = msg.toolsUsed;',
    '          if (msg.chatId === activeId) renderContextFooter();',
    '        }',
    '      }',
    '      if (msg.type === \'toolProgress\' && msg.chatId && msg.tool) {',
    '        var tc = chats.find(function (c) { return c.id === msg.chatId; });',
    '        if (tc) {',
    '          var lastMsg = tc.messages[tc.messages.length - 1];',
    '          if (lastMsg && lastMsg.typing) {',
    '            lastMsg.text = (msg.tool === \'think\' ? \'Рассуждаю...\' : \'Использую: \' + msg.tool + \'...\');',
    '            if (msg.chatId === activeId) renderMessages();',
    '          }',
    '        }',
    '      }',
    '      if (msg.type === \'thinkResult\' && msg.chatId && msg.reasoning) {',
    '        var tch = chats.find(function (c) { return c.id === msg.chatId; });',
    '        if (tch) {',
    '          var lastM = tch.messages[tch.messages.length - 1];',
    '          if (lastM && lastM.typing) {',
    '            lastM.thinkReasoning = msg.reasoning;',
    '            lastM.text = \'Анализирую задачу...\';',
    '            if (msg.chatId === activeId) renderMessages();',
    '          }',
    '        }',
    '      }',
    '      if (msg.type === \'showPlan\' && msg.plan && msg.chatId) {',
    '        renderPlanCard(msg.chatId, msg.plan);',
    '      }',
    '      if (msg.type === \'planRejected\' && msg.chatId) {',
    '        var pcard = document.getElementById(\'plan-card-\' + msg.chatId);',
    '        if (pcard) pcard.remove();',
    '      }',
    '      if (msg.type === \'showDiff\' && Array.isArray(msg.files) && msg.chatId) {',
    '        pendingDiffByChat[msg.chatId] = { files: msg.files };',
    '        if (msg.chatId === activeId) renderDiffView(msg.files); else hideDiffView(false);',
    '      }',
    '      if (msg.type === \'diffApplied\') {',
    '        hideDiffView();',
    '        if (contextFooter) contextFooter.textContent = \'Правки применены.\';',
    '        setTimeout(function () { renderContextFooter(); }, 2000);',
    '      }',
    '      if (msg.type === \'autoUserMessage\' && msg.chatId && msg.text) {',
    '        addMessageToChat(msg.chatId, msg.text, \'user\');',
    '        addTypingPlaceholder(msg.chatId);',
    '        hideDiffView();',
    '      }',
    '      if (msg.type === \'diffApplyError\' && msg.message) {',
    '        if (contextFooter) contextFooter.textContent = \'Ошибка: \' + msg.message;',
    '        setTimeout(function () { renderContextFooter(); }, 4000);',
    '      }',
    '      if (msg.type === \'insertFile\' && typeof msg.path === \'string\') {',
    '        var fromLine = typeof msg.fromLine === \'number\' ? msg.fromLine : undefined;',
    '        var toLine = typeof msg.toLine === \'number\' ? msg.toLine : undefined;',
    '        attachFile(msg.path, fromLine, toLine);',
    '        inputEl.focus();',
    '      }',
    '      if (msg.type === \'projectContextUsed\' && typeof msg.chars === \'number\') {',
    '        lastProjectContextChars = msg.chars;',
    '        renderContextFooter();',
    '      }',
    '      if (msg.type === \'indexBuildStatus\') {',
    '        indexBuildInProgress = !!msg.inProgress;',
    '        syncStarfieldOverlay();',
    '      }',
    '    });',
    '',
    '    function renderPlanCard(chatId, plan) {',
    '      var existing = document.getElementById(\'plan-card-\' + chatId);',
    '      if (existing) existing.remove();',
    '      var card = document.createElement(\'div\');',
    '      card.id = \'plan-card-\' + chatId;',
    '      card.className = \'plan-card\';',
    '      var actionLabels = { modify: \'изменить\', create: \'создать\', delete: \'удалить\', rename: \'переименовать\' };',
    '      var stepsHtml = plan.steps.map(function(s, i) {',
    '        var cls = \'plan-step plan-step--\' + s.action;',
    '        var rename = s.newFile ? \' → \' + s.newFile : \'\';',
    '        return \'<div class="\' + cls + \'"><span class="plan-step__num">\' + (i+1) + \'</span><span class="plan-step__action">\' + (actionLabels[s.action] || s.action) + \'</span><span class="plan-step__file">\' + s.file + rename + \'</span><span class="plan-step__desc">\' + s.description + \'</span></div>\';',
    '      }).join(\'\');',
    '      var notesHtml = plan.notes ? \'<div class="plan-notes">📌 \' + plan.notes + \'</div>\' : \'\';',
    '      card.innerHTML = \'<div class="plan-header"><span class="plan-title">📋 \' + plan.title + \'</span></div><div class="plan-steps">\' + stepsHtml + \'</div>\' + notesHtml + \'<div class="plan-actions"><button class="plan-btn plan-btn--confirm" id="plan-confirm-\' + chatId + \'">▶ Выполнить план</button><button class="plan-btn plan-btn--reject" id="plan-reject-\' + chatId + \'">✕ Отменить</button></div>\';',
    '      var messagesEl = document.getElementById(\'messages\');',
    '      if (messagesEl) messagesEl.appendChild(card);',
    '      document.getElementById(\'plan-confirm-\' + chatId).addEventListener(\'click\', function() {',
    '        card.remove();',
    '        vscode.postMessage({ type: \'confirmPlan\', chatId: chatId });',
    '      });',
    '      document.getElementById(\'plan-reject-\' + chatId).addEventListener(\'click\', function() {',
    '        card.remove();',
    '        vscode.postMessage({ type: \'rejectPlan\', chatId: chatId });',
    '      });',
    '      if (messagesEl) messagesEl.scrollTop = messagesEl.scrollHeight;',
    '    }',
    '',
    '    renderTabs();',
    '    renderMessages();',
    '    renderContextFooter();',
    '    vscode.postMessage({ type: \'getHistory\' });',
    '    setTimeout(function () {',
    '      loaderMinElapsed = true;',
    '      syncStarfieldOverlay();',
    '    }, 3000);',
  ];
  return lines.join('\n');
}
